AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - bin/**/*
    - db/**/*
    - lib/tasks/**
    - test/**/*
    - test/fixtures/**/*
    - tmp/**/*
    - vendor/**/*

Rails:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation